### ISSUE TITLE
Daikin Airzone

### ISSUE THREAD

**Issue by ElBielas** [max13fr/AirzoneCloud#1]
Hi max!!! The first thanks for your job, I have an Airzone dkwserver https://doc.airzone.es/producto/Fabricantes/DKN/MUAZWSDA_A5_MUL_104.pdf and login here https://dkn.airzonecloud.com . Once year ago airzone realease the new dknwserver v2 the name is Airzone Aidoo and its compatible with Alexa and Home assistant https://www.airzonecontrol.com/ib/es/soluciones_de_control/aidoo/wi-fi, but I have the first version its possible to works in Home assistant ?¿ In the case that the answer is NO, with the new version works airzone Aidoo ? Maybe I buy the new version if I can control in Home Assistant. Thanks

**Comment by max13fr** [comment]
Hello,

I checked the doc & the website, it's look like a normal airzonecloud rebranded for Daikin, so I think it should be compatible but my account doesn't work on dkn.airzonecloud.com (the database is different) so I can't test it.

I will add a base url parameter to the constructor to allow you to set dkn.airzonecloud.com and test if it's working.

Max

**Comment by ElBielas** [comment]
Hello,

Thanks very much Max !!! How can I try if work ? I can add to Home Assistant ? Or need a plugin ? Because I think your project is only the python library and we need a custom component ¿  Thanks again !!

**Comment by max13fr** [comment]
Hello,

I just pushed a new version that allowing to set a specific url for the API.

You can test by installing / upgrading the library : 

```
sudo pip3 install --upgrade airzonecloud
```

Then create a file test.py with : 

```
from AirzoneCloud import AirzoneCloud

api = AirzoneCloud("your@mail.com", "password", base_url="https://dkn.airzonecloud.com") 
for device in api.devices:
    print(device)
for zone in api.all_zones:
    print(zone)
```

Then you execute it and it should display your devices & your zones

```
python3 test.py
```

### Home assistant

This module is only a generic library to allow simple access to Airzone Cloud API.
That allows to be used by any home automation system.

I planned to create the plugin for Home Assistant but I'm running out of time unfortunatelly.
Also there is a debate if it's a good idea or not to merge Airzone direct access library and Airzone Cloud in only one Home Assistant plugin :
https://github.com/gpulido/homeassistant-airzone/issues/1#issuecomment-616178556

Personnaly, I think the configuration would risk being a mess so I think a dedicated Airzone Cloud plugin for Home Assistant should be better.

Max

**Comment by ElBielas** [comment]
ohhh you are a crack !! Yes I think its better one plugin for airzone cloud and another for bus wired. This afternoon I'm going to try to prove it. Thanks you very much !!!

**Comment by ElBielas** [comment]
:( nothing show me.....

C:\Users\Elbielas\Desktop\AirzoneCloud-0.2.0>python3 test.py

C:\Users\Elbielas\Desktop\AirzoneCloud-0.2.0>

I think Airzone have different APIs on its products. My product is an old product that dont have api I think is released in 2015 https://www.youtube.com/watch?v=DJ8FLEb4nT8 and the new product http://myzone.airzone.es/airzone-products/product-range-2016/aidoo/wi-fi/aidoo-daikin-sky-air-vrv-wi-fi-controller-604.html dont have access API only you can manage with mobile apps, dont have a site as airzonecloud.com to manage....I think I have to buy a intesishome controlller to integrate in home assistant https://www.intesishome.com/brand-specific-rc/  https://www.home-assistant.io/integrations/intesishome/

**Comment by max13fr** [comment]
Ah you are on windows, the usage differs a little (and windows hides some errors I think).

First you should install python : https://www.python.org/ftp/python/3.8.3/python-3.8.3rc1-amd64.exe
Be sure to check : 
* py launcher
* for all users
* pip
* Add Python to environment variables (on the next screen)

Then start a new terminal 

`python --version`

You should get : Python 3.8.3rc1

Now we need to install the Airzone Cloud library : 

```
pip install --upgrade airzonecloud
```

Then create a file test.py with : 

```
from AirzoneCloud import AirzoneCloud

api = AirzoneCloud("your@mail.com", "password", base_url="https://dkn.airzonecloud.com") 
for device in api.devices:
    print(device)
for zone in api.all_zones:
    print(zone)
```

Then you execute it and it should display your devices & your zones

```
python test.py
```

Max

**Comment by ElBielas** [comment]
Thanks Again !!  that's the output :( I think my airzone doesn,t have a public api.

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    api = AirzoneCloud("miuser", "mipass", base_url="https://dkn.airzonecloud.com")
  File "c:\Users\elbielas\Desktop\AirzoneCloud-0.2.0\AirzoneCloud\AirzoneCloud.py", line 46, in __init__
    self._load_devices()
  File "c:\Users\elbielas\Desktop\AirzoneCloud-0.2.0\AirzoneCloud\AirzoneCloud.py", line 102, in _load_devices
    for device_relation in self._get_device_relations():
TypeError: 'NoneType' object is not iterable

**Comment by max13fr** [comment]
There is necessary an API because it's used by the mobile app & browser website.

Unfortunatelly, without an account to test I can't try to debug your issue.
Are you ok to set a temporary password to your account and send it to me with your login ?

Max

**Comment by max13fr** [comment]
Good news, I find the time today to write the plugin for Home Assistant.

It's available here : https://github.com/max13fr/Airzonecloud-HomeAssistant

Unfortunatelly, you will have the same issue until it's fixed.

Max

**Comment by ElBielas** [comment]
Check your mail ;) 

Thanks!!!

**Comment by max13fr** [comment]
Arf we are unlucky, the API for Daikin has a lot of differences with usual Airzone Cloud API : 
* all constants are differents (hvac modes, fan speeds, ...)
* the objects & hierarchy are totaly differents : device_relation -> device -> system -> zone VS device -> installation (or the opposite ? I'm not sure). 
* many fields containing the data are different

In summary, near everything is different so it would be very hard to integrate it soon :/

Max

**Comment by ElBielas** [comment]
Thanks for your time Max !!!! Maybe in a future you can integrated ? If not I have to buy a new controller :( I can share my login the time that you need.

I found this https://www.manualslib.com/manual/1628715/Daikin-Airzone.html

http://daikinac.com/assets/DOC/OperationManuals/Operation%20Manual%20-%20MUAZWCDAU_EN_FR_ES_Final.pdf

Thanks

**Comment by max13fr** [comment]
The first doc seems to match what I saw on dkn.airzonecloud.com, just the domain name is different.

I'm not seeing a way to integrate it to this module because they are too many differences, the become would become a mess. The best approch is to create a new module dedicated to Daikin Airzone, then create a wrapper module above to abstract the complexity on both modules.
Finally the home assistant would use this wrapper module to provide a unified interface in Home Assistant.

With the API documentation, it's seem doable but unfortunatelly I'm running out of time to do it, I already have a lot of projects waiting.

Max

**Comment by ElBielas** [comment]
Ok, thanks for your time Max.

Regards

**Comment by javierinho2000** [comment]
Max, I just posted an issue on your page for Airzone Cloud custom module for HASS and then I found this issue, which is the same ElBielas has. I understand it'd be a lot of work if so many things are different, it's really very unfortunate becase I think there'd plenty of people using it.

Is there anything I can do to help (my Python knowledge is really basic).

**Comment by ElBielas** [comment]
It would be great news if you could adapt it. A lot of people use dknwserver of airzone. Thankssss

**Comment by max13fr** [comment]
Yes I understand. Unfortunately it needs to develop a completely new plugin to support Daikin (there are many hours to be expected and I also need to work to feed my family).

I will try to find some free time to do a prototype but currently I free time.

Max

**Comment by javierinho2000** [comment]
of course :-) Anyway, if you need beta testers I'm sure you have two willing candidates here :-)

**Comment by ElBielas** [comment]
I can give you an user of my dknwserver to test it if you need. Javier eres de España, no ?

**Comment by max13fr** [comment]
Good news, I found some time to write the specfic library to Daikin AirzoneCloud.

It's available here : https://github.com/max13fr/AirzoneCloudDaikin

The next step is to create a wrapper library on AirzoneCloud & AirzoneCloudDaikin library to provide a unified interface to use for homes automations softwares. And finally, to adapt my home assistant plugin to use this unified library.

Max

**Comment by ElBielas** [comment]
I don't beleive it, It works !!!!!!!!!!!!!!!! Thanks max13fr you are a phenomenon. At the moment the library is in python, but you still have to do the integration in HA or I could already use it in HA ? Thanks again, thankssssssssssssss

**Comment by javierinho2000** [comment]
Agreed with ElBielas :-) Amazing job!
