### ISSUE TITLE
airzone access

### ISSUE THREAD

**Issue by jfdoube** [max13fr/AirzoneCloud#3]
Hi,

Is it possible to connect to the airzone controller within the wifi network ?

Thank you

**Comment by vibragiel** [comment]
Yes, the Airzone webserver should be listening on port 3000. This is the API documentation (sorry, Spanish only): https://doc.airzone.es/producto/Gama_AZ6/Airzone/Comunes/Manuales/MI_AZ6_WSCLAPI_A4_ES.pdf

**Comment by max13fr** [comment]
Hi, sorry for the delay.

The airzone webserver is available directly from lan only for the wired version, not for the wifi version unfortunatelly (confirmed by airzone support and my personnal reverse engineering).

Max

**Comment by vibragiel** [comment]
Hi @max13fr. I don't know exactly what hardware and software versions the Airzone support person you contacted is referring to, but the following response is from the Wi-Fi module I got installed last week (no wires involved):

```
$ curl -d '{"systemID": 1, "zoneID": 1}' -H 'Content-Type: application/json' http://192.168.0.118:3000/api/v1/hvac
{
	"data":	[{
			"systemID":	1,
			"zoneID":	1,
			"name":	"Dormitorio",
			"on":	0,
			"maxTemp":	30,
			"minTemp":	18,
			"setpoint":	27.500000,
			"roomTemp":	23.500000,
			"modes":	[1, 4, 2, 3, 5],
			"mode":	2,
			"coldStages":	1,
			"coldStage":	1,
			"heatStages":	1,
			"heatStage":	1,
			"humidity":	45,
			"units":	0,
			"errors":	[],
			"air_demand":	0,
			"floor_demand":	0
		}]
}
```

I didn't have to do anything special to enable this.
