### ISSUE TITLE
set.temperature()

### ISSUE THREAD

**Issue by thundershare** [max13fr/AirzoneCloud#5]
Hi @max13fr,

when I try to use set_temperature(), the system not set the temperature that I pass but the default target temperature.

Ex: if I try zone.set_temperature(21.0) the system set 22, if I try zone.set_temperature(21.5) the system set 22, if I try zone.set_temperature(19)... the system set 22 ^_^'

All other commands work fine

Thanks for any suggestions

**Comment by max13fr** [comment]
Hello,

Just release a new version using the official Airzone API.

Can you upgrade and retry ?

Max
