### ISSUE TITLE
No up-to-date data retrieved

### ISSUE THREAD

**Issue by nightcatnl** [max13fr/AirzoneCloud#6]
I use the API to retrieve status of my climate system
Every 5 mins I request zone info from the AirzoneCloud and store information in my influx / grafana setup.

It seems requested data is not up-to-date. However after accessing the AirzoneCloud with the app and do a request again via the python script the data is up-to-date.

What can cause this issue ?

**Comment by nightcatnl** [comment]
I am using several refresh options and also the ask_airzone_update

Is there an example available of how this should work (to fetch up-to-date temperature and humidity data)

**Comment by max13fr** [comment]
Hello,

I just released a new version using the official Airzone API : https://developers.airzonecloud.com/docs/web-api/

That should fix this issue so I close it.

Max
