### ISSUE TITLE
New web on july

### ISSUE THREAD

**Issue by Fonsos** [max13fr/AirzoneCloud#7]
Hi, I work at Airzone and I this is the only way I found to contact you about this project.

In the coming weeks, airzonecontrol.com is going to change and we think this will broke our project. We would we would like to talk with you to improve the project with oficial documentation.

If you don't mind, please contact us at infoapps[a]airzone.es

Thank you in advance.

**Comment by ukrolelo** [comment]
Greetings, thank you for leting us know. On what date will be new UI implemented? So i can just incase turn off the component until it is fixed. Will airzonecloud.com be also touched/changed?

**Comment by Fonsos** [comment]
Hello,
From July 19th users will be able to start using the new application and their credentials for the current airzonecontrol.com will no longer be valid.
From July 26th, the new web version will be available.

We would like you to contact us at infoapps[a]airzone.es so we can explain you how to use the official API and work together.

Thanks!

**Comment by ukrolelo** [comment]
Will airzonecloud.com be also touched/changed?

**Comment by Fonsos** [comment]
Yes, everything will be changed.

Please, contact us at infoapps[a]airzone.es

**Comment by ukrolelo** [comment]
> Yes, everything will be changed.
> 
> Please, contact us at infoapps[a]airzone.es

It seems it is down already,right?
I did sent you an email. No reply.
Feel free to paste here info? Maybe other developer will go with it?

**Comment by ukrolelo** [comment]
Does your local API work?
https://github.com/jrhbcn/HomeAssistant-airzone_local/blob/master/webserver_local_api_MI_AZ6_WSCLAPI_A4_EN.pdf
:3000/api/v1/integration
Gives me:
{"errors":[{"error":"Method not provided or not supported"}]}

**Comment by ukrolelo** [comment]
:3000/api/v1/integration
{"systemid":1,"zoneid":1}
{"errors":[{"error":"request malformed"}]}
Why

**Comment by Fonsos** [comment]
If the user has updated the app, now the old app and the web won't work for the user.

I'll talk to my bosses so the can answer to your mail as soon as possible. Sorry for the inconvenience.

**Comment by ukrolelo** [comment]
No problem, thank you for follow up.
https://m.airzonecloud.com
is working with my credentials.
Can you explain to me, why local API is not working. Technician is not able to come for over a month....
:3000/api/v1/integration
{"systemid":1,"zoneid":1}
{"errors":[{"error":"request malformed"}]}

**Comment by Fonsos** [comment]
I'm sorry, I'm just the only Home Assistant user working at Airzone and the only one that knew the existence of this Community integrations, also I'm not a dev.
I'll try to get you the answer as soon as possible talking to my bosses.

**Comment by max13fr** [comment]
Thanks for your help.

For information, I sent a mail several weeks ago, I got a first reply but without the doc.

I replied but I didn't get any news since (I relaunched few days ago without success currently).

Max

PS : sorry my spare time is really low currently, I hope to find some times in August during my holidays

**Comment by fjhorrillo** [comment]
Me too, I have another plug-in for home kit but after first answer, nobody contact me again

**Comment by victordlsb** [comment]
Hi all,

another one that was using this API, in my case for a custom alexa skill as my server is pre2016. Any update from Airzone on the new API? 

Thanks btw for the work done so far!

**Comment by gabrio79** [comment]
> Hi, I work at Airzone and I this is the only way I found to contact you about this project.
> 
> In the coming weeks, airzonecontrol.com is going to change and we think this will broke our project. We would we would like to talk with you to improve the project with oficial documentation.
> 
> If you don't mind, please contact us at infoapps[a]airzone.es
> 
> Thank you in advance.

Hi Fonsos, where I can find the new API guideline?

**Comment by Fonsos** [comment]
I'm sorry but this is all the information I have at this moment:

> We are writing the documentation about it (with the API commands of our new backend and apps), we will release it and we will ensure that it will always continue to work as specified.
> 
> As soon as we have this documentation ready, we will share it with you and publish it.

**Comment by vesppetto** [comment]
I have the same problem, it is not working since a few days. 
Anyway, I am happy to see that user @Fonsos knows it and they are working to fix it.
Looking forward to have good news soon. Thanks!

**Comment by ukrolelo** [comment]
Ofcourse,turn old api off and then prepare docs for new xD this is exactly why we dont push new programs on PLC until all the manuals are finished :-P

**Comment by jrhbcn** [comment]
@Fonsos Any news on the new API documentation from airzone?

**Comment by plouf34** [comment]
It should had been solved 2 weeks ago…

**Comment by gabrio79** [comment]
@Fonsos Any news on the new API documentation from airzone?

**Comment by Fonsos** [comment]
I have asked internally and the answer is:
We have never had an official API or official documentation on the API used internally. We expect to have some documentation of the new API starting in October.

**Comment by gabrio79** [comment]
hi asked to support and received this
https://doc.airzone.es/producto/Gama_AZ6/Airzone/Comunes/Manuales/MI_AZ6_WSCLAPI_A4_MUL.pdf
@max13fr i hope that could be useful

**Comment by max13fr** [comment]
Hello,

Local API is only available on some hardwares (like airzone wired ethernet or some new wifi cards released this year). If it's your case, you can try this project : https://github.com/gpulido/python-airzone

Else, if you hardware only support external api (airzone cloud), currently we don't have any solution as they stopped the previous API and don't release the new public API ... It's coming "soon" (since two months).

Max

**Comment by gabrio79** [comment]
it's strange... i have 2 web server, one only Local API are running...
I'm not a programmer so I'm not sure to be able to manage https://github.com/gpulido/python-airzone and integrate them in homeassistant...
but thanks

**Comment by jrhbcn** [comment]
Hello,

> Local API is only available on some hardwares (like airzone wired ethernet or some new wifi cards released this year). 

Local API has also stopped working for me (working fine before with airzone wired Ethernet card). I don't know what caused it,  the new app upgrade or a new firmware upgrade from support (to try to solve un unrelated error 12) but one of the two broke the local API for me.

I really hope airzone can release a new "unofficial" or "official" API soon enough. I might try to undust my Wireshark computer and try to break their API but I would rather airzone releases some docs for us.

**Comment by gabrio79** [comment]
I have 2 web server, one with FW 3.173 local api is running, on the second one with FW 3.2 doesn't works (3000 port it seems closed)

**Comment by max13fr** [comment]
The airzone local api integration for home assistant is available : https://github.com/gpulido/homeassistant-airzone

Indeed, it's really strange that local API doesnt work since the update, but I didn't have any information, my hardware wifi card only support remote API.

**Comment by jrhbcn** [comment]
> I have 2 web server, one with FW 3.173 local api is running, on the second one with FW 3.2 doesn't works (3000 port it seems closed)

That seems consistent also with my setup. Local API dos not work on new FW and port 3000 seems closed.

**Comment by gabrio79** [comment]
I asked to support..

**Comment by gabrio79** [comment]
> > I have 2 web server, one with FW 3.173 local api is running, on the second one with FW 3.2 doesn't works (3000 port it seems closed)
> 
> That seems consistent also with my setup. Local API dos not work on new FW and port 3000 seems closed.

I asked to support.. and the answer was:
on your system with FW 3.2, the local API wasn't installed... now they installed latest 3.36 and works :-)

I think that new FW introduce new features, now the app has several color
![Screen Shot 2021-08-11 at 16 37 10](https://user-images.githubusercontent.com/65911264/129049447-52565a8f-bb2a-4b6f-9d48-181c46331479.png)
blu --> cool
green--> comfort
gray-->off

**Comment by supertabouret** [comment]
> 
> I asked to support.. and the answer was:
> on your system with FW 3.2, the local API wasn't installed... now they installed latest 3.36 and works :-)

Hello @gabrio79 

I have FW 3.2 right now. How do i update firmware to 3.36 please ?

**Comment by gabrio79** [comment]
Hello, I wrote email to airzone technical support

Il Gio 12 Ago 2021, 08:20 supertabouret ***@***.***> ha
scritto:

**Comment by aimartin** [comment]
Is there any noticeable improvements in the newer version?

**Comment by gabrio79** [comment]
> Is there any noticeable improvements in the newer version?

3.36 respect 3.2 I don't know.. respect 3.173 yes, local api provide now system name (but also in 3.2)

**Comment by ukrolelo** [comment]
I am calling technical department.....Good that i have unlimited calls :D waiting 12minutes now... :-P

**Comment by aimartin** [comment]
Ask them for a Release Notes for the firmwares xDD

**Comment by ukrolelo** [comment]
Well its 45 minutes, as i called again and ask why so long,they said only 1 person speak english.. @aimartin Roger that
Update 1:
Okay, its been over an hour. I need to go AFK, will continue later... :d

**Comment by Fonsos** [comment]
@ukrolelo since Wednesday, almost everyone is on holiday 🤷‍♂️
The 25th is when several of us will go back to the office.

**Comment by ukrolelo** [comment]
@Fonsos Thx for info.
Yeah and working hours are until 14:30 i missed the time...Will try tomorrow :>
Enjoy your vacation <3

**Comment by ukrolelo** [comment]
Okay so this is the latest manual
https://doc.airzone.es/producto/Gama_AZ6/Airzone/Comunes/Manuales/MI_AZ6_WSCLAPI_A4_MUL.pdf
Reguarding the docs i did'nt ask :-O, was so happy that they sorted it out.
The problem was old firmware or wrong header in post. So they clicked everything, the most important was content-length from what i have tested. Now i'm going to try the localairzone package if it will work :-D

**Comment by ukrolelo** [comment]
![Screenshot_191](https://user-images.githubusercontent.com/60402662/130219449-77aaf65f-8e2a-4b87-98e1-85a394f4e060.png)

**Comment by gabrio79** [comment]
> Okay so this is the latest manual
> https://doc.airzone.es/producto/Gama_AZ6/Airzone/Comunes/Manuales/MI_AZ6_WSCLAPI_A4_MUL.pdf
> Reguarding the docs i did'nt ask :-O, was so happy that they sorted it out.
> The problem was old firmware or wrong header in post. So they clicked everything, the most important was content-length from what i have tested. Now i'm going to try the localairzone package if it will work :-D

currently I'm using it... little bit different (not cool, heat mode but only heat_cool on zone) so I adjusted my automation/script and now is working (locally)
I asked some additional features in naming convention as Max approach

**Comment by ukrolelo** [comment]
Yeah dofferent, but its not showing corectly room temps and i see all is off. Which os not. Strange ... i dont think will have any more time for that. Will need to wait or put some issue on github to the localapi project :-X

**Comment by ukrolelo** [comment]
sooo it seams that there is a problem with local API .....
Giving me the same readings the whole day...
Will contact support....
{
"data": [{
"systemID": 2,
"zoneID": 2,
"name": "Kancelar",
"on": 0,
"maxTemp": 30,
"minTemp": 18,
"setpoint": 25,
"roomTemp": 25.900000,
"mode": 2,
"coldStages": 1,
"coldStage": 1,
"heatStages": 2,
"heatStage": 2,
"humidity": 65,
"units": 0,
"errors": [],
"air_demand": 0,
"floor_demand": 0
}]
}

**Comment by fjhorrillo** [comment]
Hi, base on the analysis on the new web I have gotten some information.

1. Login is with oauth but it is easy:
POST https://m.airzonecloud.com/api/v1/auth/login
{ "email": "{{email}}", "password": "{{password}}" }
From the response get token

2. Get Installations:
GET https://m.airzonecloud.com/api/v1/installations
HEADER authorization=Bearer {{token}}
From the response get installations[0].installation_id (where 0 is the index of the installation you want, by default 0)

3. Get Installation detail:
GET https://m.airzonecloud.com/api/v1/installations/{{installationId}}
HEADER authorization=Bearer {{token}}
From the response get the Device List

4. Turn On/Off:
PATCH https://m.airzonecloud.com/api/v1/devices/{{deviceId}}
HEADER authorization=Bearer {{token}}
{ "param": "power", "value": true, "installation_id": "{{installationId}}" }

5. Set temperture:
PATCH https://m.airzonecloud.com/api/v1/devices/{{deviceId}}
HEADER authorization=Bearer {{token}}
{ "param": "setpoint_air_cool", "value": {{temerture}}, "installation_id": "{{installationId}}", "opts": { "units": 0 } }
Depend on the mode use: setpoint_air_cool, setpoint_air_heat, setpoint_air_vent or setpoint_air_dry

6. Set mode:
PATCH https://m.airzonecloud.com/api/v1/devices/{{deviceId}}
HEADER authorization=Bearer {{token}}
{ "param": "mode", "value": 0, "installation_id": "{{installationId}}" }
Modes: 0 (Stop), 2 (Cool), 3 (Heat), 4 (Fan) or 5 (Dry)

7a. Get device info (sync):
GET https://{{base_url}}/api/v1/devices/{{deviceId}}/config?installation_id={{installationId}}&type=all
HEADER authorization=Bearer {{token}}

7b. Get device info (async):
For this, it is necessary to use websocket
wss://m.airzonecloud.com/api/v1/websockets/conn/?jwt={{token}}&EIO=4&transport=websocket
After conect send the messages:
40
422["clear_listeners"]
421["listen_installation","{{installationId}}"]
You will get the device status for all systems and zones

Regards,
Javier Horrillo

**Comment by matnoublanche** [comment]
Hi again,

I also follow another issue that you replied on

max13fr/AirzoneCloud#7

You find all this by reverse engineering or someone finally respond on the Airzone team ?

**Comment by fjhorrillo** [comment]
Hi, I’ve finally started using reverse engineering.

**Comment by ukrolelo** [comment]
So i spoke to technician, the problem was that the API was stucked. They restarted the API and ask me if it will repeat again i should call.
I can confirm that this local airzone homeassistant custom components is working
https://github.com/gpulido/homeassistant-airzone
All is fine, lets hope it sticks this way :smile:

**Comment by magefesa** [comment]
How to find port, idevice id ancd class? ? Thanks in advacne

**Comment by ukrolelo** [comment]
This is my settings:
climate:
  - platform: airzone
    host: 192.168.x.x
    port: 3000
    device_id: 1
    device_class: localapi

**Comment by magefesa** [comment]
> This is my settings:
> climate:
> 
> * platform: airzone
>   host: 192.168.x.x
>   port: 3000
>   device_id: 1
>   device_class: localapi

Thank you !! All works like a charm !

**Comment by romero091** [comment]
good afternoon, I was able to connect via LocalAPI to Airzone.
This integration creates a card for the machine, where you can choose the operating mode (cold, heat, fan) and a card for each zone, showing the temperature and turning it on or off.
is there a way to show the humidity of the thermostats?
Can the fan speed be adjusted individually in each zone?
Thanks for your help.

**Comment by ukrolelo** [comment]
This is airzonecloud, you shold write issue on  localapi github.

**Comment by gabrio79** [comment]
> good afternoon, I was able to connect via LocalAPI to Airzone.
> This integration creates a card for the machine, where you can choose the operating mode (cold, heat, fan) and a card for each zone, showing the temperature and turning it on or off.
> is there a way to show the humidity of the thermostats?
> Can the fan speed be adjusted individually in each zone?
> Thanks for your help.

hello, independently from local or cloud api, you can define a sensor template like 
`{{ state_attr('climate.casa_soggiorno', 'current_humidity') }} `
or visualize them in a markdown (here [https://github.com/gpulido/homeassistant-airzone/issues/13#issuecomment-896995468](url) an example

**Comment by Jibe13** [comment]
Hello, do you have news ?

**Comment by Nicodemus78** [comment]
Hi!
I tried to follow your suggestions but I get this error.
what do you suggest me to do?
I have a AZX6WSBSCLOUD LAN card.
Thanks

![Schermata 2021-11-05 alle 21 29 58](https://user-images.githubusercontent.com/18264106/140574804-6d069851-4766-47e4-8a56-df70e6857fc3.png)
![Schermata 2021-11-05 alle 21 30 12](https://user-images.githubusercontent.com/18264106/140575090-ccf7ddb8-7d64-49de-8931-b4106ae335f3.png)

**Comment by gbuico** [comment]
@Nicodemus78 
if you are getting that error it means that the Webserver is not answering your request.
This can be for several reason:
- wrong ip address or ip address not reachable (just try to ping)
- a whatever firewall rule
... but the most probable one is that the port 3000 of he WebServer is not open

To debug, I suggest that you first try, as described in the localAPI manual:

The POST method is used to extract the data of a specified zone.
This method is used as below:
POST http://XXX.XXX.XXX.XX:3000/api/v1/hvac
Where XXX.XXX.XXX.XX is the IP address of the Airzone Webserver.
The port by default is 3000.
The application where is pointed is api/v1/hvac.
With the following body
{
“systemID”: n (system number),
“zoneID”: m (zone number)
}



If also here you get a message saying Connection error or similar, then you need to call Airzone support and have them:
- update your firmware (3.36 in my case)
- do whatever is needed to have port 3000 answer the localAPI calls

**Comment by max13fr** [comment]
Hello,

I just released a new version using the official Airzone API : https://developers.airzonecloud.com/docs/web-api/

You can try it, just set your email & password in config_test.json then run : 

```
./test.py
```

It should list all your installations, groups and devices. It's all fresh, so there are risks of bugs or changes.

Have fun,
Max

**Comment by Nicodemus78** [comment]
A thousand thanks .  I solved it by entering Port 3000
